language: node_js
node_js:
  - "stable"

branches:
  only:
    - "master"

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - jharkins67@gmail.com
      - nmun2615@gmail.com
